language: python
python:
    - 2.7
    - 2.6

install: 
    - travis_retry pip install -r pip-req.txt

script:
    - echo 'Run test...'
    - python flaskr_tests.py

before_deploy:
    - zip -r latest *
    - mkdir -p dpl_cd_upload
    - mv latest.zip dpl_cd_upload/latest.zip
    - ls -al dpl_cd_upload/

#deploy:
    #- provider: codedeploy
        #access_key_id: "YOUR AWS ACCESS KEY"
        #secret_access_key: "YOUR AWS SECRET KEY"
        #bucket: "S3 Bucket"
        #key: latest/MyApp.zip
        #application: MyApp
        #deployment_group: MyDeploymentGroup
